// Autogenerated by Thrift for thrift/test/testset/testset.thrift
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//  @generated

package testset

import (
	"context"
	"errors"
	"fmt"
	"io"
	"reflect"
	"sync"

	metadata "example.com/hello/internal/metadata"
	thrift "example.com/hello/internal/types"
)

// (needed to ensure safety because of naive import list construction)
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = io.EOF
var _ = reflect.Ptr
var _ = sync.OnceFunc
var _ = thrift.VOID
var _ = metadata.GoUnusedProtection__
