// Autogenerated by Thrift for thrift/test/testset/testset.thrift
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//  @generated

package testset

import (
	thrift "example.com/hello/internal/types"
)

// (needed to ensure safety because of naive import list construction)
var _ = thrift.VOID

var GoUnusedProtection__ int
