// Autogenerated by Thrift for thrift/lib/thrift/metadata.thrift
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//  @generated

package metadata

import (
	thrift "example.com/hello/internal/types"
)

// (needed to ensure safety because of naive import list construction)
var _ = thrift.VOID

// Premade codec specs
var (
	premadeCodecTypeSpec_metadata_ThriftPrimitiveType = &thrift.TypeSpec{
		FullName: "metadata.ThriftPrimitiveType",
		CodecEnumSpec: &thrift.CodecEnumSpec{
			ScopedName: "metadata.ThriftPrimitiveType",
		},
	}
	premadeCodecTypeSpec_metadata_ThriftConstValue = &thrift.TypeSpec{
		FullName: "metadata.ThriftConstValue",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftConstValue",
			IsUnion:    true,
			NewFunc:    func() thrift.Struct { return NewThriftConstValue() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftConstValuePair = &thrift.TypeSpec{
		FullName: "metadata.ThriftConstValuePair",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftConstValuePair",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftConstValuePair() },
		},
	}
	premadeCodecTypeSpec_bool = &thrift.TypeSpec{
		FullName: "bool",
		CodecPrimitiveSpec: &thrift.CodecPrimitiveSpec{
			PrimitiveType: thrift.CODEC_PRIMITIVE_TYPE_BOOL,
		},
	}
	premadeCodecTypeSpec_i64 = &thrift.TypeSpec{
		FullName: "i64",
		CodecPrimitiveSpec: &thrift.CodecPrimitiveSpec{
			PrimitiveType: thrift.CODEC_PRIMITIVE_TYPE_I64,
		},
	}
	premadeCodecTypeSpec_double = &thrift.TypeSpec{
		FullName: "double",
		CodecPrimitiveSpec: &thrift.CodecPrimitiveSpec{
			PrimitiveType: thrift.CODEC_PRIMITIVE_TYPE_DOUBLE,
		},
	}
	premadeCodecTypeSpec_string = &thrift.TypeSpec{
		FullName: "string",
		CodecPrimitiveSpec: &thrift.CodecPrimitiveSpec{
			PrimitiveType: thrift.CODEC_PRIMITIVE_TYPE_STRING,
		},
	}
	premadeCodecTypeSpec_list_metadata_ThriftConstValuePair = &thrift.TypeSpec{
		FullName: "list<metadata.ThriftConstValuePair>",
		CodecListSpec: &thrift.CodecListSpec{
			ElementWireType: thrift.STRUCT,
			ElementTypeSpec: premadeCodecTypeSpec_metadata_ThriftConstValuePair,
		},
	}
	premadeCodecTypeSpec_list_metadata_ThriftConstValue = &thrift.TypeSpec{
		FullName: "list<metadata.ThriftConstValue>",
		CodecListSpec: &thrift.CodecListSpec{
			ElementWireType: thrift.STRUCT,
			ElementTypeSpec: premadeCodecTypeSpec_metadata_ThriftConstValue,
		},
	}
	premadeCodecTypeSpec_metadata_ThriftConstStruct = &thrift.TypeSpec{
		FullName: "metadata.ThriftConstStruct",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftConstStruct",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftConstStruct() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftStructType = &thrift.TypeSpec{
		FullName: "metadata.ThriftStructType",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftStructType",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftStructType() },
		},
	}
	premadeCodecTypeSpec_map_string_metadata_ThriftConstValue = &thrift.TypeSpec{
		FullName: "map<string, metadata.ThriftConstValue>",
		CodecMapSpec: &thrift.CodecMapSpec{
			KeyTypeSpec:   premadeCodecTypeSpec_string,
			ValueTypeSpec: premadeCodecTypeSpec_metadata_ThriftConstValue,
			KeyWireType:   thrift.STRING,
			ValueWireType: thrift.STRUCT,
		},
	}
	premadeCodecTypeSpec_metadata_ThriftType = &thrift.TypeSpec{
		FullName: "metadata.ThriftType",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftType",
			IsUnion:    true,
			NewFunc:    func() thrift.Struct { return NewThriftType() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftListType = &thrift.TypeSpec{
		FullName: "metadata.ThriftListType",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftListType",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftListType() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftSetType = &thrift.TypeSpec{
		FullName: "metadata.ThriftSetType",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftSetType",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftSetType() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftMapType = &thrift.TypeSpec{
		FullName: "metadata.ThriftMapType",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftMapType",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftMapType() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftEnumType = &thrift.TypeSpec{
		FullName: "metadata.ThriftEnumType",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftEnumType",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftEnumType() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftUnionType = &thrift.TypeSpec{
		FullName: "metadata.ThriftUnionType",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftUnionType",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftUnionType() },
		},
	}
	premadeCodecTypeSpec_list_metadata_ThriftConstStruct = &thrift.TypeSpec{
		FullName: "list<metadata.ThriftConstStruct>",
		CodecListSpec: &thrift.CodecListSpec{
			ElementWireType: thrift.STRUCT,
			ElementTypeSpec: premadeCodecTypeSpec_metadata_ThriftConstStruct,
		},
	}
	premadeCodecTypeSpec_metadata_ThriftTypedefType = &thrift.TypeSpec{
		FullName: "metadata.ThriftTypedefType",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftTypedefType",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftTypedefType() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftStreamType = &thrift.TypeSpec{
		FullName: "metadata.ThriftStreamType",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftStreamType",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftStreamType() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftSinkType = &thrift.TypeSpec{
		FullName: "metadata.ThriftSinkType",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftSinkType",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftSinkType() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftBidiType = &thrift.TypeSpec{
		FullName: "metadata.ThriftBidiType",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftBidiType",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftBidiType() },
		},
	}
	premadeCodecTypeSpec_i32 = &thrift.TypeSpec{
		FullName: "i32",
		CodecPrimitiveSpec: &thrift.CodecPrimitiveSpec{
			PrimitiveType: thrift.CODEC_PRIMITIVE_TYPE_I32,
		},
	}
	premadeCodecTypeSpec_map_i32_string = &thrift.TypeSpec{
		FullName: "map<i32, string>",
		CodecMapSpec: &thrift.CodecMapSpec{
			KeyTypeSpec:   premadeCodecTypeSpec_i32,
			ValueTypeSpec: premadeCodecTypeSpec_string,
			KeyWireType:   thrift.I32,
			ValueWireType: thrift.STRING,
		},
	}
	premadeCodecTypeSpec_metadata_ThriftEnum = &thrift.TypeSpec{
		FullName: "metadata.ThriftEnum",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftEnum",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftEnum() },
		},
	}
	premadeCodecTypeSpec_map_string_string = &thrift.TypeSpec{
		FullName: "map<string, string>",
		CodecMapSpec: &thrift.CodecMapSpec{
			KeyTypeSpec:   premadeCodecTypeSpec_string,
			ValueTypeSpec: premadeCodecTypeSpec_string,
			KeyWireType:   thrift.STRING,
			ValueWireType: thrift.STRING,
		},
	}
	premadeCodecTypeSpec_metadata_ThriftField = &thrift.TypeSpec{
		FullName: "metadata.ThriftField",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftField",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftField() },
		},
	}
	premadeCodecTypeSpec_list_metadata_ThriftField = &thrift.TypeSpec{
		FullName: "list<metadata.ThriftField>",
		CodecListSpec: &thrift.CodecListSpec{
			ElementWireType: thrift.STRUCT,
			ElementTypeSpec: premadeCodecTypeSpec_metadata_ThriftField,
		},
	}
	premadeCodecTypeSpec_metadata_ThriftStruct = &thrift.TypeSpec{
		FullName: "metadata.ThriftStruct",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftStruct",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftStruct() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftException = &thrift.TypeSpec{
		FullName: "metadata.ThriftException",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftException",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftException() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftFunction = &thrift.TypeSpec{
		FullName: "metadata.ThriftFunction",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftFunction",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftFunction() },
		},
	}
	premadeCodecTypeSpec_list_metadata_ThriftFunction = &thrift.TypeSpec{
		FullName: "list<metadata.ThriftFunction>",
		CodecListSpec: &thrift.CodecListSpec{
			ElementWireType: thrift.STRUCT,
			ElementTypeSpec: premadeCodecTypeSpec_metadata_ThriftFunction,
		},
	}
	premadeCodecTypeSpec_metadata_ThriftService = &thrift.TypeSpec{
		FullName: "metadata.ThriftService",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftService",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftService() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftModuleContext = &thrift.TypeSpec{
		FullName: "metadata.ThriftModuleContext",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftModuleContext",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftModuleContext() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftServiceContext = &thrift.TypeSpec{
		FullName: "metadata.ThriftServiceContext",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftServiceContext",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftServiceContext() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftServiceContextRef = &thrift.TypeSpec{
		FullName: "metadata.ThriftServiceContextRef",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftServiceContextRef",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftServiceContextRef() },
		},
	}
	premadeCodecTypeSpec_metadata_ThriftMetadata = &thrift.TypeSpec{
		FullName: "metadata.ThriftMetadata",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftMetadata",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftMetadata() },
		},
	}
	premadeCodecTypeSpec_list_metadata_ThriftServiceContextRef = &thrift.TypeSpec{
		FullName: "list<metadata.ThriftServiceContextRef>",
		CodecListSpec: &thrift.CodecListSpec{
			ElementWireType: thrift.STRUCT,
			ElementTypeSpec: premadeCodecTypeSpec_metadata_ThriftServiceContextRef,
		},
	}
	premadeCodecTypeSpec_metadata_ThriftServiceMetadataResponse = &thrift.TypeSpec{
		FullName: "metadata.ThriftServiceMetadataResponse",
		CodecStructSpec: &thrift.CodecStructSpec{
			ScopedName: "metadata.ThriftServiceMetadataResponse",
			IsUnion:    false,
			NewFunc:    func() thrift.Struct { return NewThriftServiceMetadataResponse() },
		},
	}
	premadeCodecTypeSpec_map_string_metadata_ThriftEnum = &thrift.TypeSpec{
		FullName: "map<string, metadata.ThriftEnum>",
		CodecMapSpec: &thrift.CodecMapSpec{
			KeyTypeSpec:   premadeCodecTypeSpec_string,
			ValueTypeSpec: premadeCodecTypeSpec_metadata_ThriftEnum,
			KeyWireType:   thrift.STRING,
			ValueWireType: thrift.STRUCT,
		},
	}
	premadeCodecTypeSpec_map_string_metadata_ThriftStruct = &thrift.TypeSpec{
		FullName: "map<string, metadata.ThriftStruct>",
		CodecMapSpec: &thrift.CodecMapSpec{
			KeyTypeSpec:   premadeCodecTypeSpec_string,
			ValueTypeSpec: premadeCodecTypeSpec_metadata_ThriftStruct,
			KeyWireType:   thrift.STRING,
			ValueWireType: thrift.STRUCT,
		},
	}
	premadeCodecTypeSpec_map_string_metadata_ThriftException = &thrift.TypeSpec{
		FullName: "map<string, metadata.ThriftException>",
		CodecMapSpec: &thrift.CodecMapSpec{
			KeyTypeSpec:   premadeCodecTypeSpec_string,
			ValueTypeSpec: premadeCodecTypeSpec_metadata_ThriftException,
			KeyWireType:   thrift.STRING,
			ValueWireType: thrift.STRUCT,
		},
	}
	premadeCodecTypeSpec_map_string_metadata_ThriftService = &thrift.TypeSpec{
		FullName: "map<string, metadata.ThriftService>",
		CodecMapSpec: &thrift.CodecMapSpec{
			KeyTypeSpec:   premadeCodecTypeSpec_string,
			ValueTypeSpec: premadeCodecTypeSpec_metadata_ThriftService,
			KeyWireType:   thrift.STRING,
			ValueWireType: thrift.STRUCT,
		},
	}
)

// Premade struct specs
var (
	premadeStructSpec_ThriftConstValuePair = &thrift.StructSpec{
		Name:        "ThriftConstValuePair",
		ScopedName:  "metadata.ThriftConstValuePair",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRUCT,
				Name:                 "key",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftConstValue,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "value",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftConstValue,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
		},
		FieldSpecNameToIndex: map[string]int{
			"key":   0,
			"value": 1,
		},
	}
	premadeStructSpec_ThriftConstValue = &thrift.StructSpec{
		Name:        "ThriftConstValue",
		ScopedName:  "metadata.ThriftConstValue",
		IsUnion:     true,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.BOOL,
				Name:                 "cv_bool",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_bool,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   2,
				WireType:             thrift.I64,
				Name:                 "cv_integer",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_i64,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   3,
				WireType:             thrift.DOUBLE,
				Name:                 "cv_double",
				ReflectIndex:         2,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_double,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   4,
				WireType:             thrift.STRING,
				Name:                 "cv_string",
				ReflectIndex:         3,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   5,
				WireType:             thrift.LIST,
				Name:                 "cv_map",
				ReflectIndex:         4,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftConstValuePair,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   6,
				WireType:             thrift.LIST,
				Name:                 "cv_list",
				ReflectIndex:         5,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftConstValue,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   7,
				WireType:             thrift.STRUCT,
				Name:                 "cv_struct",
				ReflectIndex:         6,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftConstStruct,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
			3: 2,
			4: 3,
			5: 4,
			6: 5,
			7: 6,
		},
		FieldSpecNameToIndex: map[string]int{
			"cv_bool":    0,
			"cv_integer": 1,
			"cv_double":  2,
			"cv_string":  3,
			"cv_map":     4,
			"cv_list":    5,
			"cv_struct":  6,
		},
	}
	premadeStructSpec_ThriftConstStruct = &thrift.StructSpec{
		Name:        "ThriftConstStruct",
		ScopedName:  "metadata.ThriftConstStruct",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRUCT,
				Name:                 "type",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftStructType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   2,
				WireType:             thrift.MAP,
				Name:                 "fields",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_map_string_metadata_ThriftConstValue,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
		},
		FieldSpecNameToIndex: map[string]int{
			"type":   0,
			"fields": 1,
		},
	}
	premadeStructSpec_ThriftListType = &thrift.StructSpec{
		Name:        "ThriftListType",
		ScopedName:  "metadata.ThriftListType",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRUCT,
				Name:                 "valueType",
				ReflectIndex:         0,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
		},
		FieldSpecNameToIndex: map[string]int{
			"valueType": 0,
		},
	}
	premadeStructSpec_ThriftSetType = &thrift.StructSpec{
		Name:        "ThriftSetType",
		ScopedName:  "metadata.ThriftSetType",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRUCT,
				Name:                 "valueType",
				ReflectIndex:         0,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
		},
		FieldSpecNameToIndex: map[string]int{
			"valueType": 0,
		},
	}
	premadeStructSpec_ThriftMapType = &thrift.StructSpec{
		Name:        "ThriftMapType",
		ScopedName:  "metadata.ThriftMapType",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRUCT,
				Name:                 "keyType",
				ReflectIndex:         0,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "valueType",
				ReflectIndex:         1,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
		},
		FieldSpecNameToIndex: map[string]int{
			"keyType":   0,
			"valueType": 1,
		},
	}
	premadeStructSpec_ThriftEnumType = &thrift.StructSpec{
		Name:        "ThriftEnumType",
		ScopedName:  "metadata.ThriftEnumType",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRING,
				Name:                 "name",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
		},
		FieldSpecNameToIndex: map[string]int{
			"name": 0,
		},
	}
	premadeStructSpec_ThriftStructType = &thrift.StructSpec{
		Name:        "ThriftStructType",
		ScopedName:  "metadata.ThriftStructType",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRING,
				Name:                 "name",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
		},
		FieldSpecNameToIndex: map[string]int{
			"name": 0,
		},
	}
	premadeStructSpec_ThriftUnionType = &thrift.StructSpec{
		Name:        "ThriftUnionType",
		ScopedName:  "metadata.ThriftUnionType",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRING,
				Name:                 "name",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
		},
		FieldSpecNameToIndex: map[string]int{
			"name": 0,
		},
	}
	premadeStructSpec_ThriftTypedefType = &thrift.StructSpec{
		Name:        "ThriftTypedefType",
		ScopedName:  "metadata.ThriftTypedefType",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRING,
				Name:                 "name",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "underlyingType",
				ReflectIndex:         1,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   3,
				WireType:             thrift.LIST,
				Name:                 "structured_annotations",
				ReflectIndex:         2,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftConstStruct,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
			3: 2,
		},
		FieldSpecNameToIndex: map[string]int{
			"name":                   0,
			"underlyingType":         1,
			"structured_annotations": 2,
		},
	}
	premadeStructSpec_ThriftStreamType = &thrift.StructSpec{
		Name:        "ThriftStreamType",
		ScopedName:  "metadata.ThriftStreamType",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRUCT,
				Name:                 "elemType",
				ReflectIndex:         0,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "initialResponseType",
				ReflectIndex:         1,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
		},
		FieldSpecNameToIndex: map[string]int{
			"elemType":            0,
			"initialResponseType": 1,
		},
	}
	premadeStructSpec_ThriftSinkType = &thrift.StructSpec{
		Name:        "ThriftSinkType",
		ScopedName:  "metadata.ThriftSinkType",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRUCT,
				Name:                 "elemType",
				ReflectIndex:         0,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "finalResponseType",
				ReflectIndex:         1,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   3,
				WireType:             thrift.STRUCT,
				Name:                 "initialResponseType",
				ReflectIndex:         2,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
			3: 2,
		},
		FieldSpecNameToIndex: map[string]int{
			"elemType":            0,
			"finalResponseType":   1,
			"initialResponseType": 2,
		},
	}
	premadeStructSpec_ThriftBidiType = &thrift.StructSpec{
		Name:        "ThriftBidiType",
		ScopedName:  "metadata.ThriftBidiType",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRUCT,
				Name:                 "initialResponseType",
				ReflectIndex:         0,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "streamElemType",
				ReflectIndex:         1,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   3,
				WireType:             thrift.STRUCT,
				Name:                 "sinkElemType",
				ReflectIndex:         2,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
			3: 2,
		},
		FieldSpecNameToIndex: map[string]int{
			"initialResponseType": 0,
			"streamElemType":      1,
			"sinkElemType":        2,
		},
	}
	premadeStructSpec_ThriftType = &thrift.StructSpec{
		Name:        "ThriftType",
		ScopedName:  "metadata.ThriftType",
		IsUnion:     true,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.I32,
				Name:                 "t_primitive",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftPrimitiveType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "t_list",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftListType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   3,
				WireType:             thrift.STRUCT,
				Name:                 "t_set",
				ReflectIndex:         2,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftSetType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   4,
				WireType:             thrift.STRUCT,
				Name:                 "t_map",
				ReflectIndex:         3,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftMapType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   5,
				WireType:             thrift.STRUCT,
				Name:                 "t_enum",
				ReflectIndex:         4,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftEnumType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   6,
				WireType:             thrift.STRUCT,
				Name:                 "t_struct",
				ReflectIndex:         5,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftStructType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   7,
				WireType:             thrift.STRUCT,
				Name:                 "t_union",
				ReflectIndex:         6,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftUnionType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   8,
				WireType:             thrift.STRUCT,
				Name:                 "t_typedef",
				ReflectIndex:         7,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftTypedefType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   9,
				WireType:             thrift.STRUCT,
				Name:                 "t_stream",
				ReflectIndex:         8,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftStreamType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   10,
				WireType:             thrift.STRUCT,
				Name:                 "t_sink",
				ReflectIndex:         9,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftSinkType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   11,
				WireType:             thrift.STRUCT,
				Name:                 "t_bidi",
				ReflectIndex:         10,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftBidiType,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1:  0,
			2:  1,
			3:  2,
			4:  3,
			5:  4,
			6:  5,
			7:  6,
			8:  7,
			9:  8,
			10: 9,
			11: 10,
		},
		FieldSpecNameToIndex: map[string]int{
			"t_primitive": 0,
			"t_list":      1,
			"t_set":       2,
			"t_map":       3,
			"t_enum":      4,
			"t_struct":    5,
			"t_union":     6,
			"t_typedef":   7,
			"t_stream":    8,
			"t_sink":      9,
			"t_bidi":      10,
		},
	}
	premadeStructSpec_ThriftEnum = &thrift.StructSpec{
		Name:        "ThriftEnum",
		ScopedName:  "metadata.ThriftEnum",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRING,
				Name:                 "name",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   2,
				WireType:             thrift.MAP,
				Name:                 "elements",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_map_i32_string,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   3,
				WireType:             thrift.LIST,
				Name:                 "structured_annotations",
				ReflectIndex:         2,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftConstStruct,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
			3: 2,
		},
		FieldSpecNameToIndex: map[string]int{
			"name":                   0,
			"elements":               1,
			"structured_annotations": 2,
		},
	}
	premadeStructSpec_ThriftField = &thrift.StructSpec{
		Name:        "ThriftField",
		ScopedName:  "metadata.ThriftField",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.I32,
				Name:                 "id",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_i32,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "type",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   3,
				WireType:             thrift.STRING,
				Name:                 "name",
				ReflectIndex:         2,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   4,
				WireType:             thrift.BOOL,
				Name:                 "is_optional",
				ReflectIndex:         3,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_bool,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   5,
				WireType:             thrift.LIST,
				Name:                 "structured_annotations",
				ReflectIndex:         4,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftConstStruct,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   6,
				WireType:             thrift.MAP,
				Name:                 "unstructured_annotations",
				ReflectIndex:         5,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_map_string_string,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
			3: 2,
			4: 3,
			5: 4,
			6: 5,
		},
		FieldSpecNameToIndex: map[string]int{
			"id":                       0,
			"type":                     1,
			"name":                     2,
			"is_optional":              3,
			"structured_annotations":   4,
			"unstructured_annotations": 5,
		},
	}
	premadeStructSpec_ThriftStruct = &thrift.StructSpec{
		Name:        "ThriftStruct",
		ScopedName:  "metadata.ThriftStruct",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRING,
				Name:                 "name",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   2,
				WireType:             thrift.LIST,
				Name:                 "fields",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftField,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   3,
				WireType:             thrift.BOOL,
				Name:                 "is_union",
				ReflectIndex:         2,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_bool,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   4,
				WireType:             thrift.LIST,
				Name:                 "structured_annotations",
				ReflectIndex:         3,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftConstStruct,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
			3: 2,
			4: 3,
		},
		FieldSpecNameToIndex: map[string]int{
			"name":                   0,
			"fields":                 1,
			"is_union":               2,
			"structured_annotations": 3,
		},
	}
	premadeStructSpec_ThriftException = &thrift.StructSpec{
		Name:        "ThriftException",
		ScopedName:  "metadata.ThriftException",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRING,
				Name:                 "name",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   2,
				WireType:             thrift.LIST,
				Name:                 "fields",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftField,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   3,
				WireType:             thrift.LIST,
				Name:                 "structured_annotations",
				ReflectIndex:         2,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftConstStruct,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
			3: 2,
		},
		FieldSpecNameToIndex: map[string]int{
			"name":                   0,
			"fields":                 1,
			"structured_annotations": 2,
		},
	}
	premadeStructSpec_ThriftFunction = &thrift.StructSpec{
		Name:        "ThriftFunction",
		ScopedName:  "metadata.ThriftFunction",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRING,
				Name:                 "name",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "return_type",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftType,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   3,
				WireType:             thrift.LIST,
				Name:                 "arguments",
				ReflectIndex:         2,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftField,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   4,
				WireType:             thrift.LIST,
				Name:                 "exceptions",
				ReflectIndex:         3,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftField,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   5,
				WireType:             thrift.BOOL,
				Name:                 "is_oneway",
				ReflectIndex:         4,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_bool,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   6,
				WireType:             thrift.LIST,
				Name:                 "structured_annotations",
				ReflectIndex:         5,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftConstStruct,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
			3: 2,
			4: 3,
			5: 4,
			6: 5,
		},
		FieldSpecNameToIndex: map[string]int{
			"name":                   0,
			"return_type":            1,
			"arguments":              2,
			"exceptions":             3,
			"is_oneway":              4,
			"structured_annotations": 5,
		},
	}
	premadeStructSpec_ThriftService = &thrift.StructSpec{
		Name:        "ThriftService",
		ScopedName:  "metadata.ThriftService",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRING,
				Name:                 "name",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   2,
				WireType:             thrift.LIST,
				Name:                 "functions",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftFunction,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   3,
				WireType:             thrift.STRING,
				Name:                 "parent",
				ReflectIndex:         2,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   4,
				WireType:             thrift.LIST,
				Name:                 "structured_annotations",
				ReflectIndex:         3,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftConstStruct,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   5,
				WireType:             thrift.STRING,
				Name:                 "uri",
				ReflectIndex:         4,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
			3: 2,
			4: 3,
			5: 4,
		},
		FieldSpecNameToIndex: map[string]int{
			"name":                   0,
			"functions":              1,
			"parent":                 2,
			"structured_annotations": 3,
			"uri":                    4,
		},
	}
	premadeStructSpec_ThriftModuleContext = &thrift.StructSpec{
		Name:        "ThriftModuleContext",
		ScopedName:  "metadata.ThriftModuleContext",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRING,
				Name:                 "name",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
		},
		FieldSpecNameToIndex: map[string]int{
			"name": 0,
		},
	}
	premadeStructSpec_ThriftServiceContext = &thrift.StructSpec{
		Name:        "ThriftServiceContext",
		ScopedName:  "metadata.ThriftServiceContext",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRUCT,
				Name:                 "service_info",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftService,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "module",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftModuleContext,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
		},
		FieldSpecNameToIndex: map[string]int{
			"service_info": 0,
			"module":       1,
		},
	}
	premadeStructSpec_ThriftServiceContextRef = &thrift.StructSpec{
		Name:        "ThriftServiceContextRef",
		ScopedName:  "metadata.ThriftServiceContextRef",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRING,
				Name:                 "service_name",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_string,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "module",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftModuleContext,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
		},
		FieldSpecNameToIndex: map[string]int{
			"service_name": 0,
			"module":       1,
		},
	}
	premadeStructSpec_ThriftServiceMetadataResponse = &thrift.StructSpec{
		Name:        "ThriftServiceMetadataResponse",
		ScopedName:  "metadata.ThriftServiceMetadataResponse",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   1,
				WireType:             thrift.STRUCT,
				Name:                 "context",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftServiceContext,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   2,
				WireType:             thrift.STRUCT,
				Name:                 "metadata",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftMetadata,
				MustBeSetToSerialize: true,
			},
			{
				ID:                   3,
				WireType:             thrift.LIST,
				Name:                 "services",
				ReflectIndex:         2,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_list_metadata_ThriftServiceContextRef,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			1: 0,
			2: 1,
			3: 2,
		},
		FieldSpecNameToIndex: map[string]int{
			"context":  0,
			"metadata": 1,
			"services": 2,
		},
	}
	premadeStructSpec_ThriftMetadata = &thrift.StructSpec{
		Name:        "ThriftMetadata",
		ScopedName:  "metadata.ThriftMetadata",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   2,
				WireType:             thrift.MAP,
				Name:                 "enums",
				ReflectIndex:         0,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_map_string_metadata_ThriftEnum,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   4,
				WireType:             thrift.MAP,
				Name:                 "structs",
				ReflectIndex:         1,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_map_string_metadata_ThriftStruct,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   5,
				WireType:             thrift.MAP,
				Name:                 "exceptions",
				ReflectIndex:         2,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_map_string_metadata_ThriftException,
				MustBeSetToSerialize: false,
			},
			{
				ID:                   6,
				WireType:             thrift.MAP,
				Name:                 "services",
				ReflectIndex:         3,
				IsOptional:           false,
				ValueTypeSpec:        premadeCodecTypeSpec_map_string_metadata_ThriftService,
				MustBeSetToSerialize: false,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			2: 0,
			4: 1,
			5: 2,
			6: 3,
		},
		FieldSpecNameToIndex: map[string]int{
			"enums":      0,
			"structs":    1,
			"exceptions": 2,
			"services":   3,
		},
	}
	premadeStructSpec_reqThriftMetadataServiceGetThriftServiceMetadata = &thrift.StructSpec{
		Name:                 "reqThriftMetadataServiceGetThriftServiceMetadata",
		ScopedName:           "metadata.reqThriftMetadataServiceGetThriftServiceMetadata",
		IsUnion:              false,
		IsException:          false,
		FieldSpecs:           []thrift.FieldSpec{},
		FieldSpecIDToIndex:   map[int16]int{},
		FieldSpecNameToIndex: map[string]int{},
	}
	premadeStructSpec_respThriftMetadataServiceGetThriftServiceMetadata = &thrift.StructSpec{
		Name:        "respThriftMetadataServiceGetThriftServiceMetadata",
		ScopedName:  "metadata.respThriftMetadataServiceGetThriftServiceMetadata",
		IsUnion:     false,
		IsException: false,
		FieldSpecs: []thrift.FieldSpec{
			{
				ID:                   0,
				WireType:             thrift.STRUCT,
				Name:                 "success",
				ReflectIndex:         0,
				IsOptional:           true,
				ValueTypeSpec:        premadeCodecTypeSpec_metadata_ThriftServiceMetadataResponse,
				MustBeSetToSerialize: true,
			},
		},
		FieldSpecIDToIndex: map[int16]int{
			0: 0,
		},
		FieldSpecNameToIndex: map[string]int{
			"success": 0,
		},
	}
)

var premadeCodecSpecsMap = func() map[string]*thrift.TypeSpec {
	fbthriftTypeSpecsMap := make(map[string]*thrift.TypeSpec)
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftPrimitiveType.FullName] = premadeCodecTypeSpec_metadata_ThriftPrimitiveType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftConstValue.FullName] = premadeCodecTypeSpec_metadata_ThriftConstValue
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftConstValuePair.FullName] = premadeCodecTypeSpec_metadata_ThriftConstValuePair
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_bool.FullName] = premadeCodecTypeSpec_bool
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_i64.FullName] = premadeCodecTypeSpec_i64
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_double.FullName] = premadeCodecTypeSpec_double
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_string.FullName] = premadeCodecTypeSpec_string
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftConstStruct.FullName] = premadeCodecTypeSpec_metadata_ThriftConstStruct
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftStructType.FullName] = premadeCodecTypeSpec_metadata_ThriftStructType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftType.FullName] = premadeCodecTypeSpec_metadata_ThriftType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftListType.FullName] = premadeCodecTypeSpec_metadata_ThriftListType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftSetType.FullName] = premadeCodecTypeSpec_metadata_ThriftSetType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftMapType.FullName] = premadeCodecTypeSpec_metadata_ThriftMapType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftEnumType.FullName] = premadeCodecTypeSpec_metadata_ThriftEnumType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftUnionType.FullName] = premadeCodecTypeSpec_metadata_ThriftUnionType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftTypedefType.FullName] = premadeCodecTypeSpec_metadata_ThriftTypedefType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftStreamType.FullName] = premadeCodecTypeSpec_metadata_ThriftStreamType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftSinkType.FullName] = premadeCodecTypeSpec_metadata_ThriftSinkType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftBidiType.FullName] = premadeCodecTypeSpec_metadata_ThriftBidiType
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_i32.FullName] = premadeCodecTypeSpec_i32
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftEnum.FullName] = premadeCodecTypeSpec_metadata_ThriftEnum
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftField.FullName] = premadeCodecTypeSpec_metadata_ThriftField
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftStruct.FullName] = premadeCodecTypeSpec_metadata_ThriftStruct
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftException.FullName] = premadeCodecTypeSpec_metadata_ThriftException
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftFunction.FullName] = premadeCodecTypeSpec_metadata_ThriftFunction
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftService.FullName] = premadeCodecTypeSpec_metadata_ThriftService
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftModuleContext.FullName] = premadeCodecTypeSpec_metadata_ThriftModuleContext
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftServiceContext.FullName] = premadeCodecTypeSpec_metadata_ThriftServiceContext
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftServiceContextRef.FullName] = premadeCodecTypeSpec_metadata_ThriftServiceContextRef
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftMetadata.FullName] = premadeCodecTypeSpec_metadata_ThriftMetadata
	fbthriftTypeSpecsMap[premadeCodecTypeSpec_metadata_ThriftServiceMetadataResponse.FullName] = premadeCodecTypeSpec_metadata_ThriftServiceMetadataResponse
	return fbthriftTypeSpecsMap
}()

// GetMetadataThriftType (INTERNAL USE ONLY).
// Returns metadata TypeSpec for a given full type name.
func GetCodecTypeSpec(fullName string) *thrift.TypeSpec {
	return premadeCodecSpecsMap[fullName]
}
