// Autogenerated by Thrift for thrift/lib/thrift/metadata.thrift
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//  @generated

package metadata

import (
	"maps"

	thrift "example.com/hello/internal/types"
)

// (needed to ensure safety because of naive import list construction)
var _ = thrift.VOID
var _ = maps.Copy[map[int]int, map[int]int]

// Premade Thrift types
var (
	premadeThriftType_metadata_ThriftPrimitiveType = &ThriftType{
		TEnum: &ThriftEnumType{
			Name: "metadata.ThriftPrimitiveType",
		},
	}
	premadeThriftType_metadata_ThriftConstValue = &ThriftType{
		TUnion: &ThriftUnionType{
			Name: "metadata.ThriftConstValue",
		},
	}
	premadeThriftType_metadata_ThriftConstValuePair = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftConstValuePair",
		},
	}
	premadeThriftType_bool = &ThriftType{
		TPrimitive: thrift.Pointerize(ThriftPrimitiveType_THRIFT_BOOL_TYPE),
	}
	premadeThriftType_i64 = &ThriftType{
		TPrimitive: thrift.Pointerize(ThriftPrimitiveType_THRIFT_I64_TYPE),
	}
	premadeThriftType_double = &ThriftType{
		TPrimitive: thrift.Pointerize(ThriftPrimitiveType_THRIFT_DOUBLE_TYPE),
	}
	premadeThriftType_string = &ThriftType{
		TPrimitive: thrift.Pointerize(ThriftPrimitiveType_THRIFT_STRING_TYPE),
	}
	premadeThriftType_list_metadata_ThriftConstValuePair = &ThriftType{
		TList: &ThriftListType{
			ValueType: premadeThriftType_metadata_ThriftConstValuePair,
		},
	}
	premadeThriftType_list_metadata_ThriftConstValue = &ThriftType{
		TList: &ThriftListType{
			ValueType: premadeThriftType_metadata_ThriftConstValue,
		},
	}
	premadeThriftType_metadata_ThriftConstStruct = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftConstStruct",
		},
	}
	premadeThriftType_metadata_ThriftStructType = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftStructType",
		},
	}
	premadeThriftType_map_string_metadata_ThriftConstValue = &ThriftType{
		TMap: &ThriftMapType{
			KeyType:   premadeThriftType_string,
			ValueType: premadeThriftType_metadata_ThriftConstValue,
		},
	}
	premadeThriftType_metadata_ThriftType = &ThriftType{
		TUnion: &ThriftUnionType{
			Name: "metadata.ThriftType",
		},
	}
	premadeThriftType_metadata_ThriftListType = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftListType",
		},
	}
	premadeThriftType_metadata_ThriftSetType = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftSetType",
		},
	}
	premadeThriftType_metadata_ThriftMapType = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftMapType",
		},
	}
	premadeThriftType_metadata_ThriftEnumType = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftEnumType",
		},
	}
	premadeThriftType_metadata_ThriftUnionType = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftUnionType",
		},
	}
	premadeThriftType_list_metadata_ThriftConstStruct = &ThriftType{
		TList: &ThriftListType{
			ValueType: premadeThriftType_metadata_ThriftConstStruct,
		},
	}
	premadeThriftType_metadata_ThriftTypedefType = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftTypedefType",
		},
	}
	premadeThriftType_metadata_ThriftStreamType = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftStreamType",
		},
	}
	premadeThriftType_metadata_ThriftSinkType = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftSinkType",
		},
	}
	premadeThriftType_metadata_ThriftBidiType = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftBidiType",
		},
	}
	premadeThriftType_i32 = &ThriftType{
		TPrimitive: thrift.Pointerize(ThriftPrimitiveType_THRIFT_I32_TYPE),
	}
	premadeThriftType_map_i32_string = &ThriftType{
		TMap: &ThriftMapType{
			KeyType:   premadeThriftType_i32,
			ValueType: premadeThriftType_string,
		},
	}
	premadeThriftType_metadata_ThriftEnum = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftEnum",
		},
	}
	premadeThriftType_map_string_string = &ThriftType{
		TMap: &ThriftMapType{
			KeyType:   premadeThriftType_string,
			ValueType: premadeThriftType_string,
		},
	}
	premadeThriftType_metadata_ThriftField = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftField",
		},
	}
	premadeThriftType_list_metadata_ThriftField = &ThriftType{
		TList: &ThriftListType{
			ValueType: premadeThriftType_metadata_ThriftField,
		},
	}
	premadeThriftType_metadata_ThriftStruct = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftStruct",
		},
	}
	premadeThriftType_metadata_ThriftException = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftException",
		},
	}
	premadeThriftType_metadata_ThriftFunction = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftFunction",
		},
	}
	premadeThriftType_list_metadata_ThriftFunction = &ThriftType{
		TList: &ThriftListType{
			ValueType: premadeThriftType_metadata_ThriftFunction,
		},
	}
	premadeThriftType_metadata_ThriftService = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftService",
		},
	}
	premadeThriftType_metadata_ThriftModuleContext = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftModuleContext",
		},
	}
	premadeThriftType_metadata_ThriftServiceContext = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftServiceContext",
		},
	}
	premadeThriftType_metadata_ThriftServiceContextRef = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftServiceContextRef",
		},
	}
	premadeThriftType_metadata_ThriftMetadata = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftMetadata",
		},
	}
	premadeThriftType_list_metadata_ThriftServiceContextRef = &ThriftType{
		TList: &ThriftListType{
			ValueType: premadeThriftType_metadata_ThriftServiceContextRef,
		},
	}
	premadeThriftType_metadata_ThriftServiceMetadataResponse = &ThriftType{
		TStruct: &ThriftStructType{
			Name: "metadata.ThriftServiceMetadataResponse",
		},
	}
	premadeThriftType_map_string_metadata_ThriftEnum = &ThriftType{
		TMap: &ThriftMapType{
			KeyType:   premadeThriftType_string,
			ValueType: premadeThriftType_metadata_ThriftEnum,
		},
	}
	premadeThriftType_map_string_metadata_ThriftStruct = &ThriftType{
		TMap: &ThriftMapType{
			KeyType:   premadeThriftType_string,
			ValueType: premadeThriftType_metadata_ThriftStruct,
		},
	}
	premadeThriftType_map_string_metadata_ThriftException = &ThriftType{
		TMap: &ThriftMapType{
			KeyType:   premadeThriftType_string,
			ValueType: premadeThriftType_metadata_ThriftException,
		},
	}
	premadeThriftType_map_string_metadata_ThriftService = &ThriftType{
		TMap: &ThriftMapType{
			KeyType:   premadeThriftType_string,
			ValueType: premadeThriftType_metadata_ThriftService,
		},
	}
)

// Premade struct metadatas
var (
	premadeStructMetadata_ThriftConstValuePair = &ThriftStruct{
		Name:    "metadata.ThriftConstValuePair",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "key",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftConstValue,
			},
			&ThriftField{
				Id:         2,
				Name:       "value",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftConstValue,
			},
		},
	}
	premadeStructMetadata_ThriftConstValue = &ThriftStruct{
		Name:    "metadata.ThriftConstValue",
		IsUnion: true,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "cv_bool",
				IsOptional: false,
				Type:       premadeThriftType_bool,
			},
			&ThriftField{
				Id:         2,
				Name:       "cv_integer",
				IsOptional: false,
				Type:       premadeThriftType_i64,
			},
			&ThriftField{
				Id:         3,
				Name:       "cv_double",
				IsOptional: false,
				Type:       premadeThriftType_double,
			},
			&ThriftField{
				Id:         4,
				Name:       "cv_string",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
			&ThriftField{
				Id:         5,
				Name:       "cv_map",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftConstValuePair,
			},
			&ThriftField{
				Id:         6,
				Name:       "cv_list",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftConstValue,
			},
			&ThriftField{
				Id:         7,
				Name:       "cv_struct",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftConstStruct,
			},
		},
		StructuredAnnotations: []*ThriftConstStruct{
			&ThriftConstStruct{
				Type: &ThriftStructType{
					Name: "hack.MigrationBlockingLegacyJSONSerialization",
				},
				Fields: map[string]*ThriftConstValue{},
			},
		},
	}
	premadeStructMetadata_ThriftConstStruct = &ThriftStruct{
		Name:    "metadata.ThriftConstStruct",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "type",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftStructType,
			},
			&ThriftField{
				Id:         2,
				Name:       "fields",
				IsOptional: false,
				Type:       premadeThriftType_map_string_metadata_ThriftConstValue,
			},
		},
	}
	premadeStructMetadata_ThriftListType = &ThriftStruct{
		Name:    "metadata.ThriftListType",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "valueType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
		},
	}
	premadeStructMetadata_ThriftSetType = &ThriftStruct{
		Name:    "metadata.ThriftSetType",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "valueType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
		},
	}
	premadeStructMetadata_ThriftMapType = &ThriftStruct{
		Name:    "metadata.ThriftMapType",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "keyType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
			&ThriftField{
				Id:         2,
				Name:       "valueType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
		},
	}
	premadeStructMetadata_ThriftEnumType = &ThriftStruct{
		Name:    "metadata.ThriftEnumType",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
		},
	}
	premadeStructMetadata_ThriftStructType = &ThriftStruct{
		Name:    "metadata.ThriftStructType",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
		},
	}
	premadeStructMetadata_ThriftUnionType = &ThriftStruct{
		Name:    "metadata.ThriftUnionType",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
		},
	}
	premadeStructMetadata_ThriftTypedefType = &ThriftStruct{
		Name:    "metadata.ThriftTypedefType",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
			&ThriftField{
				Id:         2,
				Name:       "underlyingType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
			&ThriftField{
				Id:         3,
				Name:       "structured_annotations",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftConstStruct,
			},
		},
	}
	premadeStructMetadata_ThriftStreamType = &ThriftStruct{
		Name:    "metadata.ThriftStreamType",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "elemType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
			&ThriftField{
				Id:         2,
				Name:       "initialResponseType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
		},
	}
	premadeStructMetadata_ThriftSinkType = &ThriftStruct{
		Name:    "metadata.ThriftSinkType",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "elemType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
			&ThriftField{
				Id:         2,
				Name:       "finalResponseType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
			&ThriftField{
				Id:         3,
				Name:       "initialResponseType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
		},
	}
	premadeStructMetadata_ThriftBidiType = &ThriftStruct{
		Name:    "metadata.ThriftBidiType",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "initialResponseType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
			&ThriftField{
				Id:         2,
				Name:       "streamElemType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
			&ThriftField{
				Id:         3,
				Name:       "sinkElemType",
				IsOptional: true,
				Type:       premadeThriftType_metadata_ThriftType,
			},
		},
	}
	premadeStructMetadata_ThriftType = &ThriftStruct{
		Name:    "metadata.ThriftType",
		IsUnion: true,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "t_primitive",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftPrimitiveType,
			},
			&ThriftField{
				Id:         2,
				Name:       "t_list",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftListType,
			},
			&ThriftField{
				Id:         3,
				Name:       "t_set",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftSetType,
			},
			&ThriftField{
				Id:         4,
				Name:       "t_map",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftMapType,
			},
			&ThriftField{
				Id:         5,
				Name:       "t_enum",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftEnumType,
			},
			&ThriftField{
				Id:         6,
				Name:       "t_struct",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftStructType,
			},
			&ThriftField{
				Id:         7,
				Name:       "t_union",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftUnionType,
			},
			&ThriftField{
				Id:         8,
				Name:       "t_typedef",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftTypedefType,
			},
			&ThriftField{
				Id:         9,
				Name:       "t_stream",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftStreamType,
			},
			&ThriftField{
				Id:         10,
				Name:       "t_sink",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftSinkType,
			},
			&ThriftField{
				Id:         11,
				Name:       "t_bidi",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftBidiType,
			},
		},
		StructuredAnnotations: []*ThriftConstStruct{
			&ThriftConstStruct{
				Type: &ThriftStructType{
					Name: "hack.MigrationBlockingLegacyJSONSerialization",
				},
				Fields: map[string]*ThriftConstValue{},
			},
		},
	}
	premadeStructMetadata_ThriftEnum = &ThriftStruct{
		Name:    "metadata.ThriftEnum",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
			&ThriftField{
				Id:         2,
				Name:       "elements",
				IsOptional: false,
				Type:       premadeThriftType_map_i32_string,
			},
			&ThriftField{
				Id:         3,
				Name:       "structured_annotations",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftConstStruct,
			},
		},
	}
	premadeStructMetadata_ThriftField = &ThriftStruct{
		Name:    "metadata.ThriftField",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "id",
				IsOptional: false,
				Type:       premadeThriftType_i32,
			},
			&ThriftField{
				Id:         2,
				Name:       "type",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftType,
			},
			&ThriftField{
				Id:         3,
				Name:       "name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
			&ThriftField{
				Id:         4,
				Name:       "is_optional",
				IsOptional: false,
				Type:       premadeThriftType_bool,
			},
			&ThriftField{
				Id:         5,
				Name:       "structured_annotations",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftConstStruct,
			},
			&ThriftField{
				Id:         6,
				Name:       "unstructured_annotations",
				IsOptional: true,
				Type:       premadeThriftType_map_string_string,
			},
		},
	}
	premadeStructMetadata_ThriftStruct = &ThriftStruct{
		Name:    "metadata.ThriftStruct",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
			&ThriftField{
				Id:         2,
				Name:       "fields",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftField,
			},
			&ThriftField{
				Id:         3,
				Name:       "is_union",
				IsOptional: false,
				Type:       premadeThriftType_bool,
			},
			&ThriftField{
				Id:         4,
				Name:       "structured_annotations",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftConstStruct,
			},
		},
	}
	premadeStructMetadata_ThriftException = &ThriftStruct{
		Name:    "metadata.ThriftException",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
			&ThriftField{
				Id:         2,
				Name:       "fields",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftField,
			},
			&ThriftField{
				Id:         3,
				Name:       "structured_annotations",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftConstStruct,
			},
		},
	}
	premadeStructMetadata_ThriftFunction = &ThriftStruct{
		Name:    "metadata.ThriftFunction",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
			&ThriftField{
				Id:         2,
				Name:       "return_type",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftType,
			},
			&ThriftField{
				Id:         3,
				Name:       "arguments",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftField,
			},
			&ThriftField{
				Id:         4,
				Name:       "exceptions",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftField,
			},
			&ThriftField{
				Id:         5,
				Name:       "is_oneway",
				IsOptional: false,
				Type:       premadeThriftType_bool,
			},
			&ThriftField{
				Id:         6,
				Name:       "structured_annotations",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftConstStruct,
			},
		},
	}
	premadeStructMetadata_ThriftService = &ThriftStruct{
		Name:    "metadata.ThriftService",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
			&ThriftField{
				Id:         2,
				Name:       "functions",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftFunction,
			},
			&ThriftField{
				Id:         3,
				Name:       "parent",
				IsOptional: true,
				Type:       premadeThriftType_string,
			},
			&ThriftField{
				Id:         4,
				Name:       "structured_annotations",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftConstStruct,
			},
			&ThriftField{
				Id:         5,
				Name:       "uri",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
		},
	}
	premadeStructMetadata_ThriftModuleContext = &ThriftStruct{
		Name:    "metadata.ThriftModuleContext",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
		},
	}
	premadeStructMetadata_ThriftServiceContext = &ThriftStruct{
		Name:    "metadata.ThriftServiceContext",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "service_info",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftService,
			},
			&ThriftField{
				Id:         2,
				Name:       "module",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftModuleContext,
			},
		},
	}
	premadeStructMetadata_ThriftServiceContextRef = &ThriftStruct{
		Name:    "metadata.ThriftServiceContextRef",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "service_name",
				IsOptional: false,
				Type:       premadeThriftType_string,
			},
			&ThriftField{
				Id:         2,
				Name:       "module",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftModuleContext,
			},
		},
	}
	premadeStructMetadata_ThriftServiceMetadataResponse = &ThriftStruct{
		Name:    "metadata.ThriftServiceMetadataResponse",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         1,
				Name:       "context",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftServiceContext,
			},
			&ThriftField{
				Id:         2,
				Name:       "metadata",
				IsOptional: false,
				Type:       premadeThriftType_metadata_ThriftMetadata,
			},
			&ThriftField{
				Id:         3,
				Name:       "services",
				IsOptional: false,
				Type:       premadeThriftType_list_metadata_ThriftServiceContextRef,
			},
		},
	}
	premadeStructMetadata_ThriftMetadata = &ThriftStruct{
		Name:    "metadata.ThriftMetadata",
		IsUnion: false,
		Fields: []*ThriftField{
			&ThriftField{
				Id:         2,
				Name:       "enums",
				IsOptional: false,
				Type:       premadeThriftType_map_string_metadata_ThriftEnum,
			},
			&ThriftField{
				Id:         4,
				Name:       "structs",
				IsOptional: false,
				Type:       premadeThriftType_map_string_metadata_ThriftStruct,
			},
			&ThriftField{
				Id:         5,
				Name:       "exceptions",
				IsOptional: false,
				Type:       premadeThriftType_map_string_metadata_ThriftException,
			},
			&ThriftField{
				Id:         6,
				Name:       "services",
				IsOptional: false,
				Type:       premadeThriftType_map_string_metadata_ThriftService,
			},
		},
	}
)

var premadeThriftTypesMap = func() map[string]*ThriftType {
	fbthriftThriftTypesMap := make(map[string]*ThriftType)
	fbthriftThriftTypesMap["metadata.ThriftPrimitiveType"] = premadeThriftType_metadata_ThriftPrimitiveType
	fbthriftThriftTypesMap["metadata.ThriftConstValue"] = premadeThriftType_metadata_ThriftConstValue
	fbthriftThriftTypesMap["metadata.ThriftConstValuePair"] = premadeThriftType_metadata_ThriftConstValuePair
	fbthriftThriftTypesMap["bool"] = premadeThriftType_bool
	fbthriftThriftTypesMap["i64"] = premadeThriftType_i64
	fbthriftThriftTypesMap["double"] = premadeThriftType_double
	fbthriftThriftTypesMap["string"] = premadeThriftType_string
	fbthriftThriftTypesMap["metadata.ThriftConstStruct"] = premadeThriftType_metadata_ThriftConstStruct
	fbthriftThriftTypesMap["metadata.ThriftStructType"] = premadeThriftType_metadata_ThriftStructType
	fbthriftThriftTypesMap["metadata.ThriftType"] = premadeThriftType_metadata_ThriftType
	fbthriftThriftTypesMap["metadata.ThriftListType"] = premadeThriftType_metadata_ThriftListType
	fbthriftThriftTypesMap["metadata.ThriftSetType"] = premadeThriftType_metadata_ThriftSetType
	fbthriftThriftTypesMap["metadata.ThriftMapType"] = premadeThriftType_metadata_ThriftMapType
	fbthriftThriftTypesMap["metadata.ThriftEnumType"] = premadeThriftType_metadata_ThriftEnumType
	fbthriftThriftTypesMap["metadata.ThriftUnionType"] = premadeThriftType_metadata_ThriftUnionType
	fbthriftThriftTypesMap["metadata.ThriftTypedefType"] = premadeThriftType_metadata_ThriftTypedefType
	fbthriftThriftTypesMap["metadata.ThriftStreamType"] = premadeThriftType_metadata_ThriftStreamType
	fbthriftThriftTypesMap["metadata.ThriftSinkType"] = premadeThriftType_metadata_ThriftSinkType
	fbthriftThriftTypesMap["metadata.ThriftBidiType"] = premadeThriftType_metadata_ThriftBidiType
	fbthriftThriftTypesMap["i32"] = premadeThriftType_i32
	fbthriftThriftTypesMap["metadata.ThriftEnum"] = premadeThriftType_metadata_ThriftEnum
	fbthriftThriftTypesMap["metadata.ThriftField"] = premadeThriftType_metadata_ThriftField
	fbthriftThriftTypesMap["metadata.ThriftStruct"] = premadeThriftType_metadata_ThriftStruct
	fbthriftThriftTypesMap["metadata.ThriftException"] = premadeThriftType_metadata_ThriftException
	fbthriftThriftTypesMap["metadata.ThriftFunction"] = premadeThriftType_metadata_ThriftFunction
	fbthriftThriftTypesMap["metadata.ThriftService"] = premadeThriftType_metadata_ThriftService
	fbthriftThriftTypesMap["metadata.ThriftModuleContext"] = premadeThriftType_metadata_ThriftModuleContext
	fbthriftThriftTypesMap["metadata.ThriftServiceContext"] = premadeThriftType_metadata_ThriftServiceContext
	fbthriftThriftTypesMap["metadata.ThriftServiceContextRef"] = premadeThriftType_metadata_ThriftServiceContextRef
	fbthriftThriftTypesMap["metadata.ThriftMetadata"] = premadeThriftType_metadata_ThriftMetadata
	fbthriftThriftTypesMap["metadata.ThriftServiceMetadataResponse"] = premadeThriftType_metadata_ThriftServiceMetadataResponse
	return fbthriftThriftTypesMap
}()

var structMetadatas = func() []*ThriftStruct {
	fbthriftResults := make([]*ThriftStruct, 0)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftConstValuePair)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftConstValue)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftConstStruct)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftListType)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftSetType)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftMapType)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftEnumType)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftStructType)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftUnionType)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftTypedefType)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftStreamType)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftSinkType)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftBidiType)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftType)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftEnum)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftField)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftStruct)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftException)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftFunction)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftService)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftModuleContext)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftServiceContext)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftServiceContextRef)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftServiceMetadataResponse)
	fbthriftResults = append(fbthriftResults, premadeStructMetadata_ThriftMetadata)
	return fbthriftResults
}()

var exceptionMetadatas = func() []*ThriftException {
	fbthriftResults := make([]*ThriftException, 0)
	return fbthriftResults
}()

var enumMetadatas = func() []*ThriftEnum {
	fbthriftResults := make([]*ThriftEnum, 0)
	fbthriftResults = append(fbthriftResults,
		&ThriftEnum{
			Name: "metadata.ThriftPrimitiveType",
			Elements: map[int32]string{
				1:  "THRIFT_BOOL_TYPE",
				2:  "THRIFT_BYTE_TYPE",
				3:  "THRIFT_I16_TYPE",
				4:  "THRIFT_I32_TYPE",
				5:  "THRIFT_I64_TYPE",
				6:  "THRIFT_FLOAT_TYPE",
				7:  "THRIFT_DOUBLE_TYPE",
				8:  "THRIFT_BINARY_TYPE",
				9:  "THRIFT_STRING_TYPE",
				10: "THRIFT_VOID_TYPE",
			},
		},
	)
	return fbthriftResults
}()

var serviceMetadatas = func() []*ThriftService {
	fbthriftResults := make([]*ThriftService, 0)
	fbthriftResults = append(fbthriftResults,
		&ThriftService{
			Name: "metadata.ThriftMetadataService",
			Functions: []*ThriftFunction{
				&ThriftFunction{
					Name:       "getThriftServiceMetadata",
					IsOneway:   false,
					ReturnType: premadeThriftType_metadata_ThriftServiceMetadataResponse,
				},
			},
		},
	)
	return fbthriftResults
}()

// Thrift metadata for this package, as well as all of its recursive imports.
var packageThriftMetadata = func() *ThriftMetadata {
	allEnumsMap := make(map[string]*ThriftEnum)
	allStructsMap := make(map[string]*ThriftStruct)
	allExceptionsMap := make(map[string]*ThriftException)
	allServicesMap := make(map[string]*ThriftService)

	// Add enum metadatas from the current program...
	for _, enumMetadata := range enumMetadatas {
		allEnumsMap[enumMetadata.GetName()] = enumMetadata
	}
	// Add struct metadatas from the current program...
	for _, structMetadata := range structMetadatas {
		allStructsMap[structMetadata.GetName()] = structMetadata
	}
	// Add exception metadatas from the current program...
	for _, exceptionMetadata := range exceptionMetadatas {
		allExceptionsMap[exceptionMetadata.GetName()] = exceptionMetadata
	}
	// Add service metadatas from the current program...
	for _, serviceMetadata := range serviceMetadatas {
		allServicesMap[serviceMetadata.GetName()] = serviceMetadata
	}

	// Obtain Thrift metadatas from recursively included programs...
	var recursiveThriftMetadatas []*ThriftMetadata

	// ...now merge metadatas from recursively included programs.
	for _, thriftMetadata := range recursiveThriftMetadatas {
		maps.Copy(allEnumsMap, thriftMetadata.GetEnums())
		maps.Copy(allStructsMap, thriftMetadata.GetStructs())
		maps.Copy(allExceptionsMap, thriftMetadata.GetExceptions())
		maps.Copy(allServicesMap, thriftMetadata.GetServices())
	}

	return NewThriftMetadata().
		SetEnums(allEnumsMap).
		SetStructs(allStructsMap).
		SetExceptions(allExceptionsMap).
		SetServices(allServicesMap)
}()

// GetMetadataThriftType (INTERNAL USE ONLY).
// Returns metadata ThriftType for a given full type name.
func GetMetadataThriftType(fullName string) *ThriftType {
	return premadeThriftTypesMap[fullName]
}

// GetThriftMetadata returns complete Thrift metadata for current and imported packages.
func GetThriftMetadata() *ThriftMetadata {
	return packageThriftMetadata
}

// GetThriftMetadataForService returns Thrift metadata for the given service.
func GetThriftMetadataForService(scopedServiceName string) *ThriftMetadata {
	allServicesMap := packageThriftMetadata.GetServices()
	relevantServicesMap := make(map[string]*ThriftService)

	serviceMetadata := allServicesMap[scopedServiceName]
	// Visit and record all recursive parents of the target service.
	for serviceMetadata != nil {
		relevantServicesMap[serviceMetadata.GetName()] = serviceMetadata
		if serviceMetadata.IsSetParent() {
			serviceMetadata = allServicesMap[serviceMetadata.GetParent()]
		} else {
			serviceMetadata = nil
		}
	}

	return NewThriftMetadata().
		SetEnums(packageThriftMetadata.GetEnums()).
		SetStructs(packageThriftMetadata.GetStructs()).
		SetExceptions(packageThriftMetadata.GetExceptions()).
		SetServices(relevantServicesMap)
}
