// Autogenerated by Thrift for thrift/lib/thrift/metadata.thrift
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//  @generated

package metadata

import (
	"context"
	"errors"
	"fmt"
	"io"
	"reflect"
	"sync"

	thrift "example.com/hello/internal/types"
)

// (needed to ensure safety because of naive import list construction)
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = io.EOF
var _ = reflect.Ptr
var _ = sync.OnceFunc
var _ = thrift.VOID

type ThriftMetadataService interface {
	GetThriftServiceMetadata(ctx context.Context) (*ThriftServiceMetadataResponse, error)
}

type ThriftMetadataServiceClient interface {
	io.Closer
	GetThriftServiceMetadata(ctx context.Context) (*ThriftServiceMetadataResponse, error)
}

type thriftMetadataServiceClientImpl struct {
	ch thrift.RequestChannel
}

// Compile time interface enforcer
var _ ThriftMetadataServiceClient = (*thriftMetadataServiceClientImpl)(nil)

func NewThriftMetadataServiceChannelClient(channel thrift.RequestChannel) ThriftMetadataServiceClient {
	return &thriftMetadataServiceClientImpl{
		ch: channel,
	}
}

func (c *thriftMetadataServiceClientImpl) Close() error {
	return c.ch.Close()
}

func (c *thriftMetadataServiceClientImpl) GetThriftServiceMetadata(ctx context.Context) (*ThriftServiceMetadataResponse, error) {
	fbthriftReq := &reqThriftMetadataServiceGetThriftServiceMetadata{}
	fbthriftChannel := c.ch
	fbthriftResp := newRespThriftMetadataServiceGetThriftServiceMetadata()
	fbthriftErr := fbthriftChannel.SendRequestResponse(
		ctx,
		"getThriftServiceMetadata",
		fbthriftReq,
		fbthriftResp,
	)
	if fbthriftErr != nil {
		return nil, fbthriftErr
	} else if fbthriftEx := fbthriftResp.Exception(); fbthriftEx != nil {
		return nil, fbthriftEx
	}
	return fbthriftResp.GetSuccess(), nil
}

type ThriftMetadataServiceProcessor struct {
	processorFunctionMap map[string]thrift.ProcessorFunction
	functionServiceMap   map[string]string
	handler              ThriftMetadataService
}

func NewThriftMetadataServiceProcessor(handler ThriftMetadataService) *ThriftMetadataServiceProcessor {
	p := &ThriftMetadataServiceProcessor{
		handler:              handler,
		processorFunctionMap: make(map[string]thrift.ProcessorFunction),
		functionServiceMap:   make(map[string]string),
	}
	p.AddToProcessorFunctionMap("getThriftServiceMetadata", &procFuncThriftMetadataServiceGetThriftServiceMetadata{handler: handler})
	p.AddToFunctionServiceMap("getThriftServiceMetadata", "ThriftMetadataService")

	return p
}

func (p *ThriftMetadataServiceProcessor) AddToProcessorFunctionMap(key string, processorFunction thrift.ProcessorFunction) {
	p.processorFunctionMap[key] = processorFunction
}

func (p *ThriftMetadataServiceProcessor) AddToFunctionServiceMap(key, service string) {
	p.functionServiceMap[key] = service
}

func (p *ThriftMetadataServiceProcessor) GetProcessorFunction(key string) (processor thrift.ProcessorFunction) {
	return p.processorFunctionMap[key]
}

func (p *ThriftMetadataServiceProcessor) ProcessorFunctionMap() map[string]thrift.ProcessorFunction {
	return p.processorFunctionMap
}

func (p *ThriftMetadataServiceProcessor) FunctionServiceMap() map[string]string {
	return p.functionServiceMap
}

func (p *ThriftMetadataServiceProcessor) PackageName() string {
	return "metadata"
}

func (p *ThriftMetadataServiceProcessor) GetThriftMetadata() *ThriftMetadata {
	return GetThriftMetadataForService("metadata.ThriftMetadataService")
}

type procFuncThriftMetadataServiceGetThriftServiceMetadata struct {
	handler ThriftMetadataService
}

// Compile time interface enforcer
var _ thrift.ProcessorFunction = (*procFuncThriftMetadataServiceGetThriftServiceMetadata)(nil)

func (p *procFuncThriftMetadataServiceGetThriftServiceMetadata) NewReqArgs() thrift.ReadableStruct {
	return newReqThriftMetadataServiceGetThriftServiceMetadata()
}

func (p *procFuncThriftMetadataServiceGetThriftServiceMetadata) RunContext(ctx context.Context, reqStruct thrift.ReadableStruct) (thrift.WritableStruct, error) {
	result := newRespThriftMetadataServiceGetThriftServiceMetadata()
	retval, err := p.handler.GetThriftServiceMetadata(ctx)
	if err != nil {
		internalErr := fmt.Errorf("Internal error processing GetThriftServiceMetadata: %w", err)
		x := thrift.NewApplicationException(thrift.INTERNAL_ERROR, internalErr.Error())
		return x, internalErr
	}

	result.Success = retval
	return result, nil
}
